#!/bin/bash -e

USE_UPRIGHT_ORIENTATION_CONSTRAINT=false
USE_UPRIGHT_ORIENTATION_CONSTRAINT_END_ONLY=false
SPHERE_OBSTACLE_CONSTRAINT_CSV=0.0,0.5,0.1,0.15

source ./run_riemo_move_mico_demo `./left_goal`
source ./run_riemo_move_mico_demo `./right_goal`
