#!/bin/bash -e

USE_UPRIGHT_ORIENTATION_CONSTRAINT=true
USE_UPRIGHT_ORIENTATION_CONSTRAINT_END_ONLY=false
SPHERE_OBSTACLE_CONSTRAINT_CSV=0.0,0.5,0.1,0.15
OBSTACLE_LINEARIZATION_CONSTRAINT_CSV=`./linearization_up`

source ./run_riemo_move_mico_demo `./left_goal`
source ./run_riemo_move_mico_demo `./right_goal`
