#!/bin/bash -e
#
# Executes all demos

# Use with kinova-ros urdf
#arr_x_targets=(
#  ".55 .22 .1"
#  ".55 -.22 .1"
#)

# Use with NW/CMU urdf
arr_x_targets=(
  ".22 -.55 .1"
  "-.22 -.55 .1"
)

CONFIG_PKG="nw_mico_client"
CONFIG_PKG_DIR=`rospack find $CONFIG_PKG`

# Place the obstacle at the standard location.
#rosrun nw_mico_client set_obstacle_parameters 0. -.5 .1 .15

for ((i=1;i<=18;i++)); do
  CONFIG=config/mico_move_config.yaml
  TASK_CONFIG=config/demos/d_${i}.yaml
  echo
  echo "==================================================================="
  echo "Task config: $TASK_CONFIG"
  echo "==================================================================="
  echo
  echo "--------------------------------------------------------"
  echo "Task config parameters:"
  cat $CONFIG_PKG_DIR/$TASK_CONFIG
  echo "--------------------------------------------------------"
  echo
  sleep 2
  for X_TARGET in "${arr_x_targets[@]}"; do
    echo "Moving to target: $X_TARGET_CSV"
    rosrun nw_mico_client nw_mico_simple_move_client.py $TASK_CONFIG $X_TARGET
  done
done
