#!/bin/bash -e

scripts="\
  ./mico_endeff_full_behavioral_none \
  ./mico_endeff_full_behavioral_linearization_up \
  ./mico_endeff_full_behavioral_linearization_side \
   \
  ./mico_endeff_upright_behavioral_none \
  ./mico_endeff_upright_behavioral_linearization_up \
  ./mico_endeff_upright_behavioral_linearization_side \
   \
  ./mico_endeff_approach_behavioral_none \
  ./mico_endeff_approach_behavioral_linearization_up \
  ./mico_endeff_approach_behavioral_linearization_side \
   \
  ./mico_endeff_none_behavioral_none \
  ./mico_endeff_none_behavioral_linearization_up \
  ./mico_endeff_none_behavioral_linearization_side \
"

for S in $scripts
do
  echo
  echo "============================================================================="
  echo "Executing script: $S"
  echo "============================================================================="
  echo
  pause_time=4
  echo "<pausing for $pause_time seconds before starting>"
  sleep $pause_time

  eval $S
done
