#!/bin/bash -e
#
# Executes all demos

# Kinova-ros setup
#arr_x_targets=(
#  ".55 .22 .1"
#  ".55 -.22 .1"
#  ".4 .4 .1"
#  ".5 -.3 .15"
#  ".5 .3 .1"
#  ".4 -.4 .1"
#  ".45 .3 .07"
#  ".55 -.22 .1"
#)

# Different set of points for kinova-ros setup
#arr_x_targets=(
#  ".55 .22 .1"
#  ".5 -.22 .3"
#  ".3 .45 .1"
#  ".5 -.35 .15"
#  ".5 .3 .1"
#  ".35 -.4 .3"
#  ".45 .3 .17"
#  ".55 -.22 .1"
#)

#arr_x_targets=(
#  ".22 -.55 .1"
#  "-.22 -.55 .1"
#  ".4 -.4 .1"
#  "-.3 -.5 .15"
#  ".3 -.5 .1"
#  "-.4 -.4 .1"
#  ".3 -.45 .07"
#  "-.22 -.55 .1"
#)

arr_x_targets=(
  ".22 -.55 .1"
  "-.22 -.55 .1"
)

#arr_x_targets=(
#  ".22 -.55 .1"
#  ".4 -.4 .1"
#)

CONFIG_PKG="nw_mico_client"
CONFIG_PKG_DIR=`rospack find $CONFIG_PKG`

# Place the obstacle at the standard location.
#rosrun nw_mico_client set_obstacle_parameters .5 .0 .1 .15  # Kinova-ros setup
rosrun nw_mico_client set_obstacle_parameters .0 -.5 .1 .15

for ((i=1;i<=18;i++)); do
#for ((i=2;i<=2;i++)); do
#for ((i=17;i<=18;i++)); do
  if [ "$i" == "1" ]; then
    # This is always reset to the empty string after the program is run.
    Q_INIT_CSV="-0.614159,0,-0.400798,1.83805,-1.63068,1.42643,0.623563,0.623563"
  fi

  CONFIG=config/mico_move_config.yaml
  TASK_CONFIG=config/demos/d_${i}.yaml
  echo
  echo "==================================================================="
  echo "Task config: $TASK_CONFIG"
  echo "==================================================================="
  echo
  echo "--------------------------------------------------------"
  echo "Task config parameters:"
  cat $CONFIG_PKG_DIR/$TASK_CONFIG
  echo "--------------------------------------------------------"
  echo
  sleep 2
  for X_TARGET in "${arr_x_targets[@]}"; do
    echo "Moving to target: $X_TARGET_CSV"
    echo "rosrun nw_mico_client nw_mico_simple_move_client.py $TASK_CONFIG $X_TARGET"
    rosrun nw_mico_client nw_mico_simple_move_client.py $TASK_CONFIG $X_TARGET
    Q_INIT_CSV=""
  done
done
